### ISSUE TITLE
Password change via GraphQL

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/users#1]
Offer password change via GraphqlQL (only when SSO is not used). Update in Keycloak.

**Comment by schwobaseggl** [comment]
@SteinRobert 
This proves to be tricky. Keycloak has removed any API calls that allow credetial changes that are user-triggered (there used to be an endpoint taking a user access token and old and new password as payload). That leaves with mainly two options:

1. Application-initiated action (AIA)
    This sends the user to keycloak and lets them change the password there (simlar to login). Upon completion of the change they will be sent back to a provided redirect url. It seems that the password change view in keycloak can be styled to some extend.
2. Reset password via admin API
    This is still possible, but as it is the admin override, it does not verify the old password. The only way (I could find) to add verification of the old password would be to use the username/password-combination and try to obtain a token from the token endpoint using the password flow. This feels hacky, but would leave us free to have the password change form completely customized and integrated into the frontend.

**Comment by SteinRobert** [comment]
This is done. We're leveraging Keycloaks login actions.
